import type { Metadata } from "next";
import "./globals.css";
import Footer from '@/compornents/Footer';
import Link from "next/link";
import styles from '@/app/styles.module.css';
import Image from 'next/image';
import NavBar from "@/compornents/NavBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {



  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
